language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davidstu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davidstu/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-eu-west-2-848133553748"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
